test failing pipeline

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -18,11 +18,11 @@ jobs:
         - name: Check git log
           run: git log --oneline -5
         - name: Run a test
-          run: |
-            echo "Running tests..."
-            if [ -f README.md ]; then
-              echo "README.md exists!"
-            else
-              echo "README.md missing"
-              exit 1
-            fi
+        run: |
+          echo "Running tests..."
+          if [ -f thisdoesnotexist.md ]; then
+            echo "File exists! ✅"
+          else
+            echo "File missing! ❌"
+            exit 1
+          fi
